/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:90c36efc-8c9f-4d4d-83b4-44b691857a98",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_YFSmqBDN6",
    "aws_user_pools_web_client_id": "3okj55l0anaj5jo93fal829ag5",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://a4qdkphdp5curegftussg53qmy.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-yeht7eihkbc7hkz4r2pqyp2gai"
};


export default awsmobile;
